package org.example.javareservationproject.common.exception;

import java.util.ArrayList;
import java.util.List;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.ConstraintViolationException;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindException;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import lombok.extern.slf4j.Slf4j;

// generated by ChatGPT
@RestControllerAdvice
@Slf4j
public class GlobalExceptionHandler {

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handle(MethodArgumentNotValidException e,
        HttpServletRequest req) {
        log.error("[ERROR] {}: {}", e.getClass().getSimpleName(), e.getMessage(), e);

        List<ErrorItem> errors = new ArrayList<>();
        for (FieldError fe : e.getBindingResult().getFieldErrors()) {
            errors.add(new ErrorItem(fe.getField(), fe.getDefaultMessage()));
        }

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
            .body(new ErrorResponse("Validation failed", errors));
    }

    @ExceptionHandler(BindException.class)
    public ResponseEntity<ErrorResponse> handle(BindException e,
        HttpServletRequest req) {
        log.error("[ERROR] {}: {}", e.getClass().getSimpleName(), e.getMessage(), e);

        List<ErrorItem> errors = new ArrayList<>();
        for (FieldError fe : e.getBindingResult().getFieldErrors()) {
            errors.add(new ErrorItem(fe.getField(), fe.getDefaultMessage()));
        }

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
            .body(new ErrorResponse("Binding failed", errors));
    }

    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<ErrorResponse> handle(ConstraintViolationException e,
        HttpServletRequest req) {
        log.error("[ERROR] {}: {}", e.getClass().getSimpleName(), e.getMessage(), e);

        List<ErrorItem> errors = e.getConstraintViolations().stream()
            .map(v -> new ErrorItem(lastNode(v.getPropertyPath().toString()), v.getMessage()))
            .toList();

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
            .body(new ErrorResponse("Constraint violation", errors));
    }

    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<ErrorResponse> handle(BusinessException e,
        HttpServletRequest req) {
        log.error("[ERROR] {}: {}", e.getClass().getSimpleName(), e.getMessage(), e);

        return ResponseEntity.status(e.getStatus())
            .body(new ErrorResponse(e.getMessage(), List.of()));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handle(Exception e,
        HttpServletRequest req) {
        log.error("[ERROR] {}: {}", e.getClass().getSimpleName(), e.getMessage(), e);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
            .body(new ErrorResponse("Internal server error", List.of()));
    }

    private String lastNode(String path) {
        if (path == null || path.isBlank()) return null;
        int idx = path.lastIndexOf('.');
        return (idx >= 0 && idx + 1 < path.length()) ? path.substring(idx + 1) : path;
    }

    public record ErrorResponse(String message, List<ErrorItem> errors) {}
    public record ErrorItem(String field, String reason) {}
}
